version: '3.1'
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'leaseweb_servers'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'